### ISSUE TITLE
Clarification on amqp_maybe_release_buffers usage 

### ISSUE THREAD

**Issue by pinepain** [alanxz/rabbitmq-c#211]
Hi Alan,

could you provide some details on `amqp_maybe_release_buffers` (as well as `amqp_maybe_release_buffers_on_channel`) usage? 

Does library utilize buffers in continuous `amqp_simple_rpc` calls one by one or is it necessary to call `amqp_maybe_release_buffers` after each `amqp_simple_rpc`?

Am I right that it is good idea to call `amqp_maybe_release_buffers` only after dealing with potentially large read operations, say after `basic.get-ok`, `basic.return`, `basic.deliver` processing?

Maybe I'm missing something else, so if you will have time - highlight the intended usage of this function.

Thanks!

P.S.: I saw this mailing list discussion http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2013-June/027986.html but it is a bit old, so please give a note about whether all whitened there still valid or invalid.

**Comment by petersilva** [comment]
I had some weird bugs because of insufficient use of amqp_maybe_release_buffers. Adding more calls to it fixed most of it.  but it it isn't always enough... I have some code that bugs out if the frame supplied to wait_frame isn't zeroed.  the messages I have do not use headers.  After the code runs for a while, I get corrupted headers in my message.  putting bzero of the frame before the wait_frame fixed it.  I don't know if that's expected behaviour or a bug.

**Comment by petersilva** [comment]
When I have amqp_maybe_release_buffers, I get message header corruption at some random point.
If I remove it, I get thousands of messages processed with no errors.  I'm guessing that it is using more memory?  Do I need to use amqp_maybe_release_buffers, or is it OK to leave it out?

**Comment by petersilva** [comment]
I found my bobo... wasn't checking presence of AMQP_BASIC_HEADERS_FLAG... now I am, and it's fine...
