### ISSUE TITLE
Runtime error on Windows Server 2003

### ISSUE THREAD

**Issue by dhzr** [alanxz/rabbitmq-c#239]
Using rabbitmq client on Windows Server 2003 results in the following run-time error:
"The procedure entry point WSAPoll could not be located in the dynamic link library WS2_32.dll."

Additional info:
I have successfully built my rabbitmq client project for Visual Studio 2012 (v110, and v110_xp), and have successfully used the library in Windows Server 2008, and 2012; but for Windows Server 2003, I am experiencing the above-mentioned run-time error. It is seemingly caused by missing WSAPoll in WS2_32.dll for Windows versions less than 6 (Windows Vista) (https://msdn.microsoft.com/en-us/library/windows/desktop/ms741669%28v=vs.85%29.aspx).

I was wondering if this is a configuration issue, which with changing some compile-time config parameters can be resolved, or addressing this issue requires some modification in the code.

Thank you.

**Comment by alanxz** [comment]
Due to limitations on how `select()` works on certain platforms rabbitmq-c switched from using `select()` to using `poll()`. In the interest of not supporting two different code-paths, the `select()` implementation was removed at that point.

In order to make rabbitmq-c work on your platform you'll need to patch the source to get this done. The commit that removed the `select()` implementation was removed at a78aa8ab906c97dc3f4123048519a2953fa96fb2, I'd recommend starting there.
