### ISSUE TITLE
Asynchronous confirm.select

### ISSUE THREAD

**Issue by dreadworks** [alanxz/rabbitmq-c#241]
Hi!

I have a question regarding handling ACK's when the channel used for publishing is in [confirm mode](https://www.rabbitmq.com/confirms.html): Is there any way (or library support) to publish messages and consume acknowledgements  in a completely asynchronous (but not necessarily parallel) manner?

Since heartbeats are supported this should be possible in principle. Optimally, there would be an API function accepting a callback function that gets called every time an ACK arrives.

If it is not possible, my current plan would be creating some IPC method accepting to-be-published messages. Then I would create a set containing a handle to this IPC method and the socket for AMQP communication and poll on that. Is this a design that would work or is there any server-to-client communication interfering?

Thanks!

Btw.: The mailing list linked in the README seems down.

**Comment by alanxz** [comment]
Thanks for the heads-up on the mailing list link.  The RabbitMQ folks moved lists a while ago, and I've simply forgotten to update the link in the docs (done in af04748b78c8582d71c2923b4fcd608535a84157).

Currently there is no library support for dealing with async events in rabbitmq-c including publisher confirms. I do consider this a pretty big limitation with how the library works, and hopefully I'll have a chance to address this in the next quarter or two in a way that makes it useful and hopefully not that tricky to use. (FYI: heartbeats are only serviced when a call into the library is made).

When doing a purely publishing workload, the broker does not send much back to the client with the exception of publisher confirms, consumer cancellation notifications, and channel/connection exceptions. As such it is possible to do a polling read on the connection. A workaround that might work for you (depending on what your requirements are) would be to put any message consumers on their own connection, so that you effectively have a connection to send and a connection to receive messages. When sending messages periodically call `[amqp_simple_wait_frame_noblock](https://github.com/alanxz/rabbitmq-c/blob/af04748b78c8582d71c2923b4fcd608535a84157/librabbitmq/amqp.h#L1498)` with a 0 or small timeout. This will allow you to read the ack that gets sent by the broker.  A more fragile approach, but one that would require less polling of the library would be to extract the socket with `[amqp_get_sockfd](https://github.com/alanxz/rabbitmq-c/blob/af04748b78c8582d71c2923b4fcd608535a84157/librabbitmq/amqp.h#L1019) then use something like `poll`, `select` or some other mechanism to determine when the socket becomes readable then call `amqp_simple_wait_frame_noblock` to read the frame.  The reason I say fragile is that the libraries use of the socket is undefined, so implementation changes in rabbitmq-c may result in observable changes in when the socket becomes readable.

HTH

**Comment by dreadworks** [comment]
Thank you for your fast reply!

I chose the latter approach, put the socket returned by `amqp_get_sockfd` in a pollset and read all buffered frames via `amqp_simple_wait_frame_noblock`. As far as I can see, this works wonderful. Special care is needed when trying to intersperse RPC calls, though - since there might be data buffered by the library, a POLLIN is not triggered and the buffered frames must be consumed manually afterwards.
