### ISSUE TITLE
cannot compile on windowsXP

### ISSUE THREAD

**Issue by linhuifj** [alanxz/rabbitmq-c#261]
The code uses WSAPoll (https://msdn.microsoft.com/en-us/library/windows/desktop/ms741669%28v=vs.85%29.aspx) which is for windows8 /vista or higher versions of windows only.

How can I sue rabbitmq-c when I use windows XP?

**Comment by alanxz** [comment]
Current versions of rabbitmq-c will not work on WinXP. If at all possible I highly recommend updating your OS to something that isn't out of support.

I do have an open request to add back support for `select()`.  You're also welcome to use an older version of the library (v0.5.0 and older) which uses `select()` instead of `WSAPoll()`.
