### ISSUE TITLE
amq_queue_bind problem (unexpected protocol state)

### ISSUE THREAD

**Issue by bigmajk** [alanxz/rabbitmq-c#289]
Hi, I hope you could shed a little light on problem I have.

I have a client-server app where client is responsible for queue creation. Server just sends message after some processing to the queue. I wrote send_message function that, for every message, binds queue name and sends message. After running for a while I receive unexpected protocol state because at one point server can't bind queue any more.

After commenting out amqp_queue_bind I don't get that message any more.

```c
void send_message(amqp_connection_state_t conn, amqp_bytes_t queue, amqp_bytes_t message)
{
    amqp_queue_bind(conn, 1, queue, amqp_cstring_bytes(DIRECT), queue, amqp_empty_table);
    die_on_amqp_error(amqp_get_rpc_reply(conn), "Binding queue");
    die_on_error(amqp_basic_publish(conn,1, amqp_cstring_bytes(DIRECT), queue, 0, 0, NULL, message), "Publishing");
}
```

I guess multiple bindings from server side on same queue for multiple clients caused problem I had. 

The question I have is should I just call amqp_basic_publish on server side without binding queue?
Or should I perform some other action?

Thank you,
Miro

**Comment by bigmajk** [comment]
I found that I created queue queue_name on client side but not binding it. And from server side I send message to exchange "amq.direct" with routing_key = queue_name . So I had to bind on amq.direct exchange on server. And I just bind it every time I send message to client. I fixed binding on client side and there is no more need to bind queue on server side. 

I guess this is highly irregular, but it seems to me that calling bind for same queue and same exchange multiple times produces, at one point, unexpected protocol state.

**Comment by alanxz** [comment]
> The question I have is should I just call amqp_basic_publish on server side without binding queue?
RabbitMQ has an implicit binding between all queues and the default exchange (identified by the empty string). In this case there is no reason to call bind here if all you want to do is to put a message in a single queue. (its a different story if you need to use a fanout or topic exchange for example).

https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-default

That all said, its a bit strange to get getting unexpected protocol states when binding a queue. Is it possible that the queue was destroyed before the server was able to bind it (because the client got disconnected)? It might be better for the client do do the binding, then inform the server which exchange and routing key to use. This will prevent channel exceptions from being thrown if the queue goes away.
