### ISSUE TITLE
Selecting the SSL/TLS Versions 

### ISSUE THREAD

**Issue by Daemon22** [alanxz/rabbitmq-c#305]
I would like to be able to change the SSL/TLS version when connecting to the server.

From what I can see on amqp_openssl.c line 435, this is what is used:
self->ctx = SSL_CTX_new(SSLv23_client_method());

When I'm connecting to the server it is using tlsv1, I would like to change it to tlsv1.1, can I manually change this function to:
TLSv1_1_client_method()

**Comment by carlhoerberg** [comment]
Maybe migrate to [libtls in LibreSSL](http://www.openbsd.org/papers/libtls-fsec-2015/mgp00001.html) instead of using the old OpenSSL API?

**Comment by Daemon22** [comment]
How can I change the amqp_ssl_socket_new() function to use this instead of the openssl?

In other languages like C# you can specify the version like so:

    rabbitMQFactory.Ssl.Version = System.Security.Authentication.SslProtocols.Tls11;

Can we use something like this in this library?

**Comment by alanxz** [comment]
I am in agreement that rabbitmq-c should probably default to using TLS v1.2, and provide an option to use TLS v1.1 or TLS v1.0 where required.

@carlhoerberg: an interesting idea, though I'd prefer to implement it as a separate SSL backend, and continue to support OpenSSL for the time-being. The reason behind this is because currently OpenSSL can be found on more distributions and platforms than libReSSL currently.

**Comment by Daemon22** [comment]
**@alanxz**, will this be implemented in the near future?
If not, how do you suggest to use other TLS versions?

**Comment by alanxz** [comment]
I'll try and get something written in the next ~week or so.  For now your best bet is to patch rabbitmq-c so that amqp_openssl.c uses TLSv1_1 instead.

**Comment by Daemon22** [comment]
Thanks allot.
