### ISSUE TITLE
Doubt on no_ack on basic consume

### ISSUE THREAD

**Issue by allancommsl** [alanxz/rabbitmq-c#356]
Hello. I know that the no_ack flag make us have to ack the received message. I have been use the no_ack flag but did not found where I should send the ack, and even with that the queue is confirming my acks. how this works? is it when I call the amqp_consume_messsage? thanks, Allan.

**Comment by zbentley** [comment]
From the [RabbitMQ specification](https://www.rabbitmq.com/amqp-0-9-1-reference.html#domain.no-ack): 

> **no-ack**: If this field is set the server does not expect acknowledgements for messages. That is, when a message is delivered to the client the server assumes the delivery will succeed and immediately dequeues it. This functionality may increase performance but at the cost of reliability. Messages can get lost if a client dies before they are delivered to the application.

`no-ack` should be set when your code issues a `consume`. If the consume is successful (a `consume.ok` is received), messages will be pushed without acknowledgements expected. This also disables certain parts of the prefetch/`basic.qos` system.

The documentation does not state what happens when acknowledgements are sent for messages received by a consumer in `no-ack` mode.

I don't know what you mean when you say that "the queue is confirming my acks".

**Comment by zbentley** [comment]
I opened rabbitmq/rabbitmq-website#246 to clarify the documentation.

**Comment by alanxz** [comment]
This is a bug tracker and not a support forum.

If you still have questions, please ask on the [rabbitmq-c-users](https://groups.google.com/forum/#!forum/rabbitmq-c-users) or post it to [stackoverflow](http://www.stackoverflow.com) and use the [rabbitmq-c] tag.
