### ISSUE TITLE
AMQP_STATUS_TIMEOUT is observed frquently

### ISSUE THREAD

**Issue by GayatriNittala** [alanxz/rabbitmq-c#358]
Hi all,

We started using this library recently. Using this we are connecting to the RabbitMQ server. We have SSL enabled. We are observing AMQP_STATUS_TIMEOUT frequently. When we have gone through the code at some point it is returned based on some time checks and sometime for unknown reasons.
We would like to hear from you about when do we or why do we actually see this STATUS_TIMEOUT so that we can handle it properly in our application.
Any help on this is greatly appreciated.

Regards,
Gayatri

**Comment by alanxz** [comment]
This is a bug tracker and not a support forum.

If you still have questions, please ask on the [rabbitmq-c-users](https://groups.google.com/forum/#!forum/rabbitmq-c-users) or post it to [stackoverflow](http://www.stackoverflow.com) and use the [rabbitmq-c] tag.

**Comment by wangxiaokun** [comment]
Hi alanxz,

Is this problem solved? Because I also encountered the same trouble. I got a **AMQP_STATUS_TIMEOUT** when I call function amqp_consume_message. And after tracking I found that blocking at **poll** in the **amqp_poll** function. The parameter **timeout_ms** is -1.

This happens when the producer flowing without memory reach high watermark.
