### ISSUE TITLE
Memory leak using SSL/TLS

### ISSUE THREAD

**Issue by jesferman** [alanxz/rabbitmq-c#417]
Hi @alanxz,

I have just found a memory leak using SSL/TLS connection in my application with your library. This leak is also present in the examples. For instance in amqps_sendstring with valgrind:

`valgrind --leak-check=full --show-leak-kinds=all ./amqps_sendstring localhost 5671 "" queue_name message body`

I get 87,244 bytes of memory leaked when the program finishes. (I attach you a file with detailed valgrind output). I don't know if the leaks belong to your code or the openssl version I am using (OpenSSL 1.0.1f 6 Jan 2014), maybe you can know this. These leaks are not present when I don't use SSL/TLS

Tell me if you need more information, so we can solve it. And great work for this library!

rabbitmq-c version: latest in master
OS version: Ubuntu 14.04

[valgrind.txt](https://github.com/alanxz/rabbitmq-c/files/1058352/valgrind.txt)

**Comment by alanxz** [comment]
All of the reports look like they come from OpenSSL, specifically library initialization of things like error-strings. By default, the OpenSSL initialization should only happen the first time an SSL connection is used, and should last the lifetime of the program. Given these are only allocated once, they should be mostly harmless (other than noisy when running things like valgrind).

Because certain platforms allow you to unload shared libraries, rabbitmq-c keeps track of number of live connections and attempts to uninitialize OpenSSL when the number of allocated connections drops to 0.  It appears that rabbitmq-c doesn't fully uninitialize OpenSSL, we should consider whether its worth doing this: https://stackoverflow.com/a/29927669/786714.

**Comment by jesferman** [comment]
I followed your link and achieved to solve all the memory leaks. The problem was in` destroy_openssl` function. I'm not an expert in OpenSSL so maybe I am missing something. The code is working and it is able to deinitialize a SSL connection and reopen it againg later without any problem.

How do you prefer that I send you the code so you can review it and include in rabbitmq-c? Thanks

**Comment by alanxz** [comment]
Open a pull-request against this repository.

**Comment by alanxz** [comment]
Fixed in #422
