### ISSUE TITLE
About heartbeat

### ISSUE THREAD

**Issue by hehejiuhuizhe** [alanxz/rabbitmq-c#461]
Hi,I set heatbeat to 10s when log in.
Then I consume every 3 seconds.
Then I shutdown the network.
Then after about 30s,the mq server closed the connection,but my client still thought the connection was ok.
Then I recovered the network,and my client got a AMQP_STATUS_SOCKET_ERROR and then  AMQP_STATUS_CONNECTION_CLOSED and so closed the connection.
Is this behavior right?
Is that  the meaning of "Note rabbitmq-c only has partial support for heartbeats"(in .h file)?
Can client know the the connection is closed when the network has problem?

**Comment by applecandyfromsky** [comment]
I find a way:set the tcp option.
Here is some of my tcp setting:
ccw@ubuntu:/proc/sys/net/ipv4$ cat tcp_keepalive_time 
60
ccw@ubuntu:/proc/sys/net/ipv4$ cat tcp_keepalive_intvl 
15
ccw@ubuntu:/proc/sys/net/ipv4$ cat tcp_keepalive_probes 
4
ccw@ubuntu:/proc/sys/net/ipv4$ cat tcp_retries2 
8

And after about 6 or 7 minutes(because of the tcp retransmission),I got a AMQP_STATUS_SOCKET_ERROR and knew the connection was closed.

**Comment by jesferman** [comment]
Hi @applecandyfromsky and @alanxz,

I have encountered the same issue and have investigated the library code. This is the scenario:

A client that only sends messages when it receives a message from the RabbitMQ server. If the network shutdowns (intentionally or not) the AMQP connection is lost. The RabbitMQ server notices it after 2 heartbeats lost. But the client doesn't detect the lost of connectivity and think it is connected forever.

After seeing the code I saw that the client only checks and/or sends AMQP heartbeats when it publishes a message or when a message is received from the server. The problem in the scenario of @applecandyfromsky and mine is due to the client doesn't send messages actively, only in response of a message received. So when the connection is lost, the server deletes the connection, doesn't send more heartbeats nor messages which causes that the client doesn't receive messages and doesn't execute the block of code that checks heartbeats and thinks it is still connected.

I think the library should check periodically the heartbeats with an independent timer and not only when sends or receives messages. If you, @alanxz agrees with me I could try to implement it and make a pull request.

**Comment by sigiesec** [comment]
This conflicts with the basic design of librabbitmq. It does not start any threads that could perform any background activity. 

I do not understand the issue though. Your client must be polling for messages from the server periodically, which would also involve heartbeats being sent if necessary.

**Comment by applecandyfromsky** [comment]
@jesferman  @sigiesec 
Thanks for reply.
I doesn't use epoll.I just call amqp_consume_message every 3 seconds.
And when the network is done,I can't get error message until the network recover or after about 2 hours(because of the default tcp keepalive setting).
I know there is no threads perform background activity.
But I think if I has set the heartbeat, I would except that when I call amqp_consume_message, it could check if the connection is ok.However it doesn't.It just send a heartbeat to the server.
So I think this is the meaning of "Note rabbitmq-c only has partial support for heartbeats"(in .h file).(send heartbeat from client to server,no check for server to client)

**Comment by jesferman** [comment]
If you call `amqp_consume_message` periodically, there is no problem, the heartbeat check is performed and it detects when the network is down.

You only need to check the return of the function `amqp_consume_message` in this way:

```c
ret = amqp_consume_message(conn, &envelope, NULL, 0);

if (AMQP_RESPONSE_LIBRARY_EXCEPTION == ret.reply_type &&
    AMQP_STATUS_HEARTBEAT_TIMEOUT == ret.library_error ) {
  printf("HEARTBEAT TIMEOUT\n");
  /* Do something accordingly like disconnect and reconnect again */
 }
```

**Comment by applecandyfromsky** [comment]
@jesferman Yeah,I write like this,but it doesn't work!When the network has been down,the ret.library_error is still AMQP_STATUS_TIMEOUT suggesting that there is no message.And when I recover the net,it becomes AMQP_STATUS_SOCKET_ERROR.But I never saw  AMQP_STATUS_HEARTBEAT_TIMEOUT.
Could you please have a test?

**Comment by applecandyfromsky** [comment]
@jesferman OK,I know what's wrong.
I call amqp_consume_message with a timeout.
When I set the timeout to NULL like your code,I saw the AMQP_STATUS_HEARTBEAT_TIMEOUT.
But I think it's still a problem.

**Comment by manchicken** [comment]
I kinda think that the best choice here is going to be modifying the XS to use the rabbitmq-c functions for `amqp_consume_message()` and `amqp_read_message()`. There's some behavior that changed there, and I worry that we're not getting the updates from the upstream library.

Unless someone can remember a compelling reason why we _didn't_ use the supplied functions for that, I'm going to go ahead and start refactoring that stuff now. I'm disinclined to continue chasing and back-porting the changes from the upstream.
