### ISSUE TITLE
how to know the rabbitmq server down from amqp_consume_message return value amqp_rpc_reply_t?

### ISSUE THREAD

**Issue by wshn13** [alanxz/rabbitmq-c#469]
I use amqp_consume_message to consume from rabbitmq . When the mq server down or network break down, I should get notified.But ,when amqp_consume_message timeout ,the res.reply_type is  AMQP_RESPONSE_LIBRARY_EXCEPTION, **# BUT** when the mq server down the res.reply_type is also AMQP_RESPONSE_LIBRARY_EXCEPTION. how can I tell mq server down from consume timeout ?????

**Comment by YiDianerer** [comment]
aslo about amqp_consume_message,  How Can I consume one special channel ? this method Waits for a basic.deliver method on any channel.

**Comment by alanxz** [comment]
When looking at an [`amqp_rpc_reply_t`](https://github.com/alanxz/rabbitmq-c/blob/009bc4df22065d44e894d69c42aead4881ab6ca4/librabbitmq/amqp.h#L648), and `res.reply_type == AMQP_RESPONSE_LIBRARY_EXCEPTION`, look at the `library_error` field.  The `library_error` will be one of the error codes in [`amqp_status_enum`](https://github.com/alanxz/rabbitmq-c/blob/009bc4df22065d44e894d69c42aead4881ab6ca4/librabbitmq/amqp.h#L702).  `library_error` will have a value of `AMQP_STATUS_TIMEOUT`, you'll likely get an `AMQP_STATUS_SOCKET_CLOSED` if the connection is closed due to the broker being unavailable.
