### ISSUE TITLE
Reply for ACK returning with no AMQP_RESPONSE_LIBRARY_EXCEPTION and library_error AMQP_STATUS_UNEXPECTED_STATE

### ISSUE THREAD

**Issue by Lesiba-rabbit** [alanxz/rabbitmq-c#782]
I am not using the auto_ack.

I am using the core **amq_consumer.c** example (https://github.com/alanxz/rabbitmq-c/blob/master/examples/amqp_consumer.c)

The difference is on the  **amqp_basic_consume** I am setting no_ack = 1 and doing the acknowledgement after consuming and processing the message from the queue by calling amqp_basic_ack(conn, 1, envelope.delivery_tag, 0)

The reply for a sent ack arrives with 
AMQP_RESPONSE_NORMAL != ret.reply_type

and both 
AMQP_RESPONSE_LIBRARY_EXCEPTION == ret.reply_type 
and 
AMQP_STATUS_UNEXPECTED_STATE == ret.library_error 

What could I be doing wrong to receive a response for an ACK with an abnormal state?

Thanks

**Comment by alanxz** [comment]
By setting `no_ack = 1` when calling `amqp_basic_consume` you're enabling auto-acks; which means that the message is implicitly ack'd when its delivered. When you attempt to call `amqp_basic_ack` on a message received from a consumer with auto-ack enabled, this will cause the broker to return an channel exception, which is why you're getting the UNEXPECTED state.

If you want to explicitly ack each message you get after processing it - set `no_ack = 0` when calling `amqp_basic_consume`.
